/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as MarksRouteImport } from './routes/marks'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksRoute = MarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => BatchesRoute,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/batches': typeof BatchesRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/fees': typeof FeesRoute
  '/marks': typeof MarksRoute
  '/more': typeof MoreRoute
  '/papers': typeof PapersRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/batches': typeof BatchesRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/fees': typeof FeesRoute
  '/marks': typeof MarksRoute
  '/more': typeof MoreRoute
  '/papers': typeof PapersRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/batches': typeof BatchesRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/fees': typeof FeesRoute
  '/marks': typeof MarksRoute
  '/more': typeof MoreRoute
  '/papers': typeof PapersRoute
  '/reports': typeof ReportsRoute
  '/students': typeof StudentsRouteWithChildren
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/batches'
    | '/faculty'
    | '/fees'
    | '/marks'
    | '/more'
    | '/papers'
    | '/reports'
    | '/students'
    | '/batches/$batchId'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/batches'
    | '/faculty'
    | '/fees'
    | '/marks'
    | '/more'
    | '/papers'
    | '/reports'
    | '/students'
    | '/batches/$batchId'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/batches'
    | '/faculty'
    | '/fees'
    | '/marks'
    | '/more'
    | '/papers'
    | '/reports'
    | '/students'
    | '/batches/$batchId'
    | '/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  BatchesRoute: typeof BatchesRouteWithChildren
  FacultyRoute: typeof FacultyRoute
  FeesRoute: typeof FeesRoute
  MarksRoute: typeof MarksRoute
  MoreRoute: typeof MoreRoute
  PapersRoute: typeof PapersRoute
  ReportsRoute: typeof ReportsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks': {
      id: '/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof MarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof BatchesRoute
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof StudentsRoute
    }
  }
}

interface BatchesRouteChildren {
  BatchesBatchIdRoute: typeof BatchesBatchIdRoute
}

const BatchesRouteChildren: BatchesRouteChildren = {
  BatchesBatchIdRoute: BatchesBatchIdRoute,
}

const BatchesRouteWithChildren =
  BatchesRoute._addFileChildren(BatchesRouteChildren)

interface StudentsRouteChildren {
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsStudentIdRoute: StudentsStudentIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  BatchesRoute: BatchesRouteWithChildren,
  FacultyRoute: FacultyRoute,
  FeesRoute: FeesRoute,
  MarksRoute: MarksRoute,
  MoreRoute: MoreRoute,
  PapersRoute: PapersRoute,
  ReportsRoute: ReportsRoute,
  StudentsRoute: StudentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
